# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(965, 664)
        self.listView_classmethod = QtWidgets.QListView(Dialog)
        self.listView_classmethod.setGeometry(QtCore.QRect(20, 70, 291, 401))
        self.listView_classmethod.setObjectName("listView_classmethod")
        self.label_1_classandmethod = QtWidgets.QLabel(Dialog)
        self.label_1_classandmethod.setGeometry(QtCore.QRect(20, 10, 58, 16))
        self.label_1_classandmethod.setObjectName("label_1_classandmethod")
        self.label_2_lua = QtWidgets.QLabel(Dialog)
        self.label_2_lua.setGeometry(QtCore.QRect(620, 10, 121, 16))
        self.label_2_lua.setObjectName("label_2_lua")
        self.refresh_class_button = QtWidgets.QPushButton(Dialog)
        self.refresh_class_button.setGeometry(QtCore.QRect(100, 0, 100, 32))
        self.refresh_class_button.setObjectName("refresh_class_button")
        self.textEdit_lua = QtWidgets.QTextEdit(Dialog)
        self.textEdit_lua.setGeometry(QtCore.QRect(620, 30, 331, 441))
        self.textEdit_lua.setObjectName("textEdit_lua")
        self.label_3_log = QtWidgets.QLabel(Dialog)
        self.label_3_log.setGeometry(QtCore.QRect(20, 490, 111, 16))
        self.label_3_log.setObjectName("label_3_log")
        self.textBrowser_log = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_log.setGeometry(QtCore.QRect(20, 520, 811, 131))
        self.textBrowser_log.setObjectName("textBrowser_log")
        self.clear_logs_button = QtWidgets.QPushButton(Dialog)
        self.clear_logs_button.setGeometry(QtCore.QRect(60, 480, 100, 32))
        self.clear_logs_button.setObjectName("clear_logs_button")
        self.listView = QtWidgets.QListView(Dialog)
        self.listView.setGeometry(QtCore.QRect(340, 70, 256, 401))
        self.listView.setObjectName("listView")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 40, 58, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(340, 40, 71, 16))
        self.label_2.setObjectName("label_2")
        self.plainTextEdit_filterClassName = QtWidgets.QLineEdit(Dialog)
        self.plainTextEdit_filterClassName.setGeometry(QtCore.QRect(80, 40, 221, 21))
        self.plainTextEdit_filterClassName.setObjectName("plainTextEdit_filterClassName")
        self.plainTextEdit_filterMethodname = QtWidgets.QLineEdit(Dialog)
        self.plainTextEdit_filterMethodname.setGeometry(QtCore.QRect(410, 40, 181, 21))
        self.plainTextEdit_filterMethodname.setObjectName("plainTextEdit_filterMethodname")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        Dialog.setStatusTip(_translate("Dialog", "筛选类名"))
        Dialog.setWhatsThis(_translate("Dialog", "筛选类名"))
        self.label_1_classandmethod.setText(_translate("Dialog", "类与方法"))
        self.label_2_lua.setText(_translate("Dialog", "lua脚本编辑器"))
        self.refresh_class_button.setText(_translate("Dialog", "刷新所有类"))
        self.label_3_log.setText(_translate("Dialog", "日志"))
        self.clear_logs_button.setText(_translate("Dialog", "清空日志"))
        self.label.setText(_translate("Dialog", "筛选类名"))
        self.label_2.setText(_translate("Dialog", "筛选方法名"))
